### ISSUE TITLE
"allCaps" style causes tool failure

### ISSUE THREAD

**Issue by teresaelsey** [BoboFraggins/typefi2bookxml#16]
We have this cXML file which fails to convert:
https://hmhco.box.com/s/zy0knss6ssovwef06f6tdr1e50yhsba1

When the tag `<tps:style type="allCaps">` is removed, the file converts correctly.

It looks to us like the problem is with "to_upper" (should it be "upcase"?), or maybe that we have `<tps:style type="allCaps">` instead of `<tps:style type="allcaps">`? (But we're not getting a report that that's an unrecognized tag.)

Here's the full error message

```
WARNING: Nokogiri was built against LibXML version 2.9.2, but has dynamically loaded 2.9.0
typefi2bookxml version: 0.9.0
WARNING: Nokogiri was built against LibXML version 2.9.2, but has dynamically loaded 2.9.0
/Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/src/style_tag.rb:30:in `process_node': undefined method `to_upper' for "Alexander Pope":String (NoMethodError)
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/src/typefi_document.rb:49:in `parse_node!'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/src/typefi_document.rb:42:in `block in parse_node!'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/src/typefi_document.rb:42:in `parse_node!'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/src/typefi_document.rb:29:in `block (2 levels) in parse!'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/src/typefi_document.rb:29:in `block in parse!'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb:186:in `each'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/src/typefi_document.rb:25:in `each_with_index'
    from /Users/elseyt/Desktop/Typefi2BookXML_0.9.0.app/Contents/Resources/src/typefi_document.rb:25:in `parse!'
    from ./typefi2bookxml:27:in `block in run'
    from ./typefi2bookxml:15:in `each'
    from ./typefi2bookxml:15:in `run'
    from ./typefi2bookxml:63:in `<main>'
```

**Comment by teresaelsey** [comment]
Looks good, thanks!
